ecommerce/carts/urls.py
from django.urls import path
from .views import cart_home,cart_update
app_name='cart'
urlpatterns=[
       path('',cart_home,name='cart_home'),
       path('update/',cart_update,name='update'),

]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/',include('home.urls'),name='home'),
    path('products/', include('products.urls'), name='products'),
    path('search/',include('search.urls'),name='search'),
    path('cart/',include('carts.urls'),name='cart'),
    path('tag/',include('tags.urls')),


]

              # + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns=urlpatterns+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns=urlpatterns+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/home/urls.py
from .views import HomeView
from django.urls import path

urlpatterns=[

path('', HomeView,name='view'),

]

ecommerce/products/urls.py
from django.urls import path
from . import views
app_name='products'
urlpatterns=[
       path('',views.ProductListView.as_view(),name='list'),
       # path('detail/<int:pk>/',views.ProductDetailView.as_view(),name='detail'),
       path('detail/<slug:slug>/', views.ProductDetailView.as_view(), name='detail'),

       # path('products-fbv/',views.product_list_view),
       # path('products/',views.ProductListView.as_view())

]

ecommerce/products/models.py
from django.db import models
import random
import os
from django.utils.text import slugify
from django.db.models.signals import pre_save, post_save
from django.core.signals import request_finished
from django.dispatch import receiver
from django.urls import reverse

def get_filename_ext(filepath):
    base_name=os.path.basename(filepath)
    name,ext=os.path.splitext(base_name)
    return name,ext
def upload_image_path(instance,filename):
    new_file=random.randint(1,72342432)
    name,ext=get_filename_ext(filename)
    final_filename='{}{}'.format(new_file,ext)
    return "products/{}/{}".format(new_file,final_filename)

class ProductManager(models.Manager):
    def get_by_id(self,id):
        return self.get_queryset().filter(id=id)
    def get_by_slug(self,slug):
        return self.get_queryset().filter(slug=slug)

class Product(models.Model):
    name=models.CharField(max_length=50)
    descripation=models.TextField()
    price=models.DecimalField(decimal_places=2,max_digits=20)
    image=models.ImageField(upload_to=upload_image_path,null=True,blank=True)
    slug=models.SlugField(unique=True,blank=True)
    timestamp=models.DateTimeField(auto_now_add=True)
    featured=models.BooleanField(default=False)
    active=models.BooleanField(default=True)

    objects=ProductManager()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('products:detail',kwargs={'slug':self.slug})


    def save(self,*args,**kwargs):
        if not self.slug:
            self.slug=slugify(self.name)
        elif Product.objects.filter(slug=self.slug).exists():
            self.slug=slugify(self.name)+'-'+str(random.randint(1,23423))
        return super(Product,self).save(*args,**kwargs)


# @receiver(pre_save)
# def pre_save_receiver(sender, instance, *args, **kwargs):
#    slug = slugify(instance.name)
#    exists = Product.objects.filter(slug=slug).exists()
#    if not exists:
#       return slug
#    else:
#       slug = slug+str(random.int(1,424242))

ecommerce/products/views.py
from django.shortcuts import render
from django.views.generic import ListView,DetailView
from .models import Product
from carts.models import Cart
from django.http import Http404
# from carts.models import Cart
from django.db.models import Q
# from user_info.mixins import ObjectViewedMixins

class ProductListView(ListView):
    model=Product
    template_name='products/product_list.html'
    context_object_name='objects'

    # def get_queryset(self,*args,**kwargs):
    #     request=self.request
    #     queryset=Product.objects.all()
    #     return queryset
    def get_context_data(self,*args,**kwargs):
        context=super(ProductListView,self).get_context_data(*args,**kwargs)
        # context['name']='Krishn Kumar Patel'
        return context

class ProductDetailView(DetailView):
    model=Product
    template_name='products/product_detail.html'
    context_object_name='object'

    def get_context_data(self,*args,**kwargs):
        context=super(ProductDetailView,self).get_context_data(*args,**kwargs)
        cart_obj,new_obj=Cart.objects.new_or_get(self.request)
        context['cart']=cart_obj
        return context

    def get_object(self,*args,**kwargs):
        request=self.request
        slug=self.kwargs.get('slug')
        print("slug:",slug)
        try:
            instance=Product.objects.get(slug=slug)
        except Product.DoesNotExist:
            raise Http404("Product Does't exists .")
        except Product.MultipleObjectReturned:
            qs=Product.objects.filter(slug=slug)
            instance=qs.first()
        except:
            raise Http404('Not Found.')
        # object_viewed_signal(instance.__class__,instance=instance,request=request)
        return instance







# class ProductListView(ListView):
#     model = Product
#     template_name = 'products/product_list1.html'
#
#     def get_context_data(self, *args, object_list=None, **kwargs):
#         context = super(ProductListView, self).get_context_data(*args, **kwargs)
#         return context
#
# def product_list_view(request):
#     query=Product.objects.all()
#     context={
#         'object':query,
#
#     }
#     return render(request,'products/product_list1.html',context)
#
# def product_detail_view(request,pk=None,*args,**kwargs):
#     instance=Product.objects.get(pk=pk)
#     context={
#         'object':instance,
#     }
#     return render(request,'products/product_detail.html',context)

ecommerce/templates/products/product_detail.html
{% extends 'base.html' %}
{% block content %}

<div class="row">
    <div class="col-12 col-md-6">
        <h1>{{ object.name }}</h1>
            {{ timestamp|timesince }}ago
            {{ object.description|linebreaks }}<br/>
            {% if object.image %}
            <img src="{{ object.image.url }}" class="img-fluid"/>
            {% endif %}
        <div class="col-12 col-md-12">
        {% include 'products/update_cart.html' with product=object cart=cart %}
        </div>
    </div>
</div>

{% endblock %}

ecommerce/templates/products/product_list.html
{% extends 'base.html' %}
{% block title %}Product | List {% endblock %}
{% block content %}
<h1 class="text-center">List of Products</h1>
 <div class="container">
    <div class="row">
{{ name }}
        {% for obj in objects %}
    <div class="col-lg-3 col-md-6 col-sm-3">
      <!-- <div class="col col-sm-4 col-md-6 col-lg-4"> -->
        <div class="card p-3 mb-5 bg-white rounded">
          {% if obj.image %}
           <a href="{% url 'products:detail' obj.slug%}"> <img src="{{ obj.image.url }}" width="200px" height="200px" class="card-img-top" alt="photo"> </a>
          {% endif %}
            <div class="card-body">
                <dir class="container"/>
              <h5 class="card-title">{{ obj.name }}</h5>
              </div>
              </div>
            </div>
         </div>
        </div>
        {% endfor %}
      </div>
      <a href="https://google.com/">Google</a>
  </div>
 {% endblock %}

ecommerce/templates/products/product_list1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% for obj in object_list %}
{{ obj.name }} <br>
{% endfor %}
</body>
</html>

ecommerce/templates/products/update_cart.html
<form  method="POST" action="{% url 'cart:update'%}" class="form">{% csrf_token %}
      <input type="hidden" name="product_id" value="{{ product.id }}"/>
            {% if product in cart.products.all %}
            In cart <button type="submit" class="btn btn-link">Remove</button>
            {% else%}
            <button  type="submit" class="btn btn-link">Add to cart</button>
            {% endif %}

</form>
